# Generated by Django 3.1.2 on 2020-11-04 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_verify', '0003_teacherquestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherquestion',
            name='teacherbh',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='test_verify.user'),
        ),
    ]
