# Generated by Django 3.1.2 on 2020-11-06 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_verify', '0004_teacherquestion_teacherbh'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='User_zjw',
        ),
    ]
